

resilience4j.retry:
  instances:
    retryOrder:
      maxRetryAttempts: 3
      waitDuration: 5s
      #enableExponentialBackoff: true
      #exponentialBackoffMultiplier: 2
      #retryExceptions:
      #  - java.lang.RuntimeException
      #ignoreExceptions: